name: rikaz
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  # sdk: ^3.7.2
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_bloc: ^9.0.0
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  bloc: ^9.0.0
  fluttertoast: ^8.2.10

  cupertino_icons: ^1.0.8
  flame: ^1.27.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/rikaz.png"
flutter:
  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
